# Generated by Django 3.1.2 on 2020-11-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Работодатель')),
                ('logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Логотип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('page_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_up_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, choices=[('RUR', 'руб.'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUR', max_length=3, verbose_name='Валюта')),
                ('remote', models.BooleanField(blank=True, default=False, verbose_name='Можно удаленно')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Требуемый опыт')),
                ('type_of_employment', models.CharField(choices=[('f', 'Полная занятость'), ('p', 'Частичная занятость'), ('i', 'Стажировка'), ('p', 'Проектная работа'), ('v', 'Волонтерство')], default=None, max_length=1, verbose_name='Тип занятости')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('hh_id', models.IntegerField(unique=True, verbose_name='HH ID')),
                ('archived', models.BooleanField(default=False)),
                ('page_views', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.city', verbose_name='Город')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer', verbose_name='Работодатель')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='jobs.Skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='vacancies',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Job', verbose_name='Вакансии'),
        ),
    ]
